# Week 2
## Part 2: NumPy
## Video 2.2.3: Indexing NumPy Arrays

**1. Indexing NumPy Arrays**

In [2]:
# Import:
import numpy as np

In [3]:
# sime np.array definition:
z1 = np.array([1,2,3,4,5])
print(z1)

[1 2 3 4 5]


In [4]:
# example operations:
z2 = z1 + 1
print(z2)

[2 3 4 5 6]


In [5]:
# We can index NumPy arrays using python lists
index = [0,2,4]
z3 = z2[index]
print(z3)

[2 4 6]


In [6]:
# We can index NumPy arrays using another NumPy array
indexnp = np.array([0,1,2])
z4 = z2[indexnp]
print(z4)

[2 3 4]


**2. Create Boolean NumPy array**

In [7]:
# It is possible to create boolean NumPy array:
z1 = np.array([1,2,3,4,5,6,7,8])
z2 = z1 > 6
print(z2)

[False False False False False False  True  True]


**3. Indexing Boolean NumPy array**

In [8]:
z1 = np.array([1,2,3,4,5,6,7,8])
z3 = z1[z1 > 6] # creates NumPy array containing values bigger then 6
print(z2)

[False False False False False False  True  True]


In [9]:
z2 = z1 + 1
z4 = z2[z1 > 6]
print(z4)

[8 9]


**4. Sliceing to acces NumPy array**

In [10]:
z1 = np.array([1,2,3,4,5,6,7,8])

w = z1[0:3] # slice [0:3] element = 0,1,2 elemt of the array
print(w)

[1 2 3]


In [11]:
w[0] = 3
print(w)

[3 2 3]


In [12]:
print(z1) # first element has changed !!! - same array

[3 2 3 4 5 6 7 8]


**5. Indexing to acces NumPy array**

In [13]:
z1 = np.array([1,2,3,4,5,6,7,8])

ind = np.array([0,1,2])
w = z1[ind]
print(w)
w[0] = 3
print(w)
print(z1) # first element stayed the same !!! - coppy of the array

[1 2 3]
[3 2 3]
[1 2 3 4 5 6 7 8]


## Video 2.2.4: Building and Examining NumPy Arrays

**1. Linearly spaced NumPy Arrays**

In [14]:
import numpy as np

In [15]:
z1 = np.linspace(0,100,10)
print(z1)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


**2. Log spaced NumPy Arrays**

In [16]:
z2 = np.logspace(1, 2, 10) # firs and last element has to be log - log(10) = 1; log(100) = 2; num of elements 10 !!!
print(z2)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [17]:
# it is more clear to use np.log10 to calculate values at the point.
z2 = np.logspace(np.log10(250), np.log10(500), 10)
print(z2)

[250.         270.01493472 291.63225989 314.98026247 340.19750004
 367.43362307 396.85026299 428.62199143 462.93735614 500.        ]


**3. Shape of an NumPy Arrays**

In [18]:
X = np.array([[1,2,3],[4,5,6]])

shape = X.shape # shape of the array !!! Shape and Size are the data atributes not methods! so no () at the end.
print(shape)

size = X.size # num of elements in the array !!! Shape and Size are the data atributes not methods! so no () at the end.
print(size)

(2, 3)
6


**3. Ex, random NumPy Arrays**

In [22]:
# generate 10 random numbres from 0-1 range
x = np.random.random(10)

anybig = np.any(x>0.9) # is anny of the elements of the x array bigger then 0.9
allbig = np.all(x>0.5) # are all the lements of the x array bigger then 0.9

print(x)
print(anybig)
print(allbig)

[0.69295974 0.1613541  0.22225099 0.27567838 0.28446862 0.23313009
 0.11151121 0.62490454 0.87761667 0.26147471]
False
False


In [23]:
#Example - Is x a prime number ?
x=20 
not np.any([x%i == 0 for i in range(2, x)])

False